# test comment 7

[csls_heartbeat]
"csls_data_stream_dev"                                                     = { index = "test_data"                      , sourcetype = "csls_data_stream_dev"                                               }

[HOSTWHO]
"LOGWHAT"                                                                  = { index = "test_data"                      , sourcetype = "LOGWHAT"                                                            }
"LOG[REGX]+"                                                               = { index = "test_data"                      , sourcetype = "LOGWHAT" }

# Please leave this here:
# This ensures our tests are iterating over the full TOML file
[1111111111]
"/aws/foo/bar"                                                             = { index = "test_data"                 , sourcetype = "aws:foo:bar"                                                             }
"/rex/(?P<service>[^/]+)/(?P<loggroup>[^/]+)"                              = { index = "test_data"                 , sourcetype = "rex:$service:$loggroup"                                                  }
