name: Convert Cloudwatch routing TOML to JSON

on:
  push:
    branches: [master]
    paths:
      - "kinesis_processor/accounts_loggroup_index.toml"
  pull_request:
    branches: [bau-update-toml-routing-file]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.x"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"
      - name: Install TOML library
        working-directory: ./kinesis_processor
        run: pip install toml
      - name: Convert TOML to JSON for the routing file
        working-directory: ./kinesis_processor
        run: python convert_cloudwatch_routing_toml_to_json.py
      - name: Commit converted file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Converted TOML to JSON
